### ISSUE TITLE
Programmatically set the arc's value, 

### ISSUE THREAD

**Issue by giladHaimov** [Triggertrap/SeekArc#11]
I am new to this forum. I apologize if this is not the right place for such questions..

 My question: is there a way/workaround/whatever that will
allow me to programmatically set the arc's current value, 
something like seekArc.setValue(val);

Thanks,
Gilad
giladha@gmail.com

**Comment by scottyab** [comment]
As @pakerfeldt correctly mentions `seekArc.setProgress(progress);`. Also I've recently added fix in v1.1 to ensure you can set the progress via xml `app:progress="30"` see in updated [sample](https://github.com/Triggertrap/SeekArc/blob/master/SeekArc_sample/res/layout/activity_disabled.xml#L42-42)
