### ISSUE TITLE
SeekArc with two different color

### ISSUE THREAD

**Issue by sahir** [Triggertrap/SeekArc#12]
Hello @neild001 ,
can u plz help me out 
![img_0292](https://cloud.githubusercontent.com/assets/452706/3522996/f053d826-0752-11e4-9195-215cbd0cf044.PNG)

I want to fill two colors in a curve. As I attached screen shot of here you can see two colors (one is gray and attached red colored line). I can draw gray curve line but not able to draw red line which is attached with gray line.
So requested you to plz tell me about fill curve with two different color.

**Comment by Perry-RU** [comment]
Couldn't you just set a seekArc on top of another seekArc and adjust the padding on one to make it slightly larger than the other?
