### ISSUE TITLE
Setting up the Seekarc in eclipse android project

### ISSUE THREAD

**Issue by finndesolace** [TriggerTrap/SeekArc#17]
Hi,

I want to make an app for android 4.4 and implement the seekarc.
So I've taken these actions:
copy Seekarc into my res folder.
Either the com.triggertrap.seekarc  or my own com.example.seekarktest

I copied the drawables and the xml there in a not standard present folder "drawable"
copied the png's also in xhdpi to be sure, just in case.

I copied the values, attr, colors and styles

Anyway  i end up in an unbound prefix parsing error , adding
<com.example.seekarctest.SeekArc  Or com.triggertrap.seekarc.SeekArc  in the activity_main layout results in an unbound prefix error.

I work with eclipse, am new to android.  Did my best to import your lib and project, but there's no eclipse support for running the imported gradle projects.

Could you help me out?

**Comment by finndesolace** [comment]
I found it.  Clearly mistake cause of my lack of experience.   Deriving from the "creating a custom view" topic on the android dev site,  i found that the namespace has to be used accordingly in the layout
 xmlns:seekarc="http://schemas.android.com/apk/res/com.example.seekarctest"
or the analog triggertrap path.
as the variables in the view in the layout xml use the seekarc namespace.

**Comment by OlivierGre** [comment]
This is an old topic but I post this message for the one trying to use this widget.

In your xml file, you should add 
`    xmlns:seekarc="http://schemas.android.com/apk/res-auto"`
for example after 
`  xmlns:tools="http://schemas.android.com/tools"`

Don't forget to update your build.gradle files:

In top build.gradle file:
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```

In app build.gradle file:

`    implementation 'com.github.Triggertrap:SeekArc:v1.1'`
