### ISSUE TITLE
How to implement??

### ISSUE THREAD

**Issue by AndroidDoctorr** [Triggertrap/SeekArc#27]
I added exactly what it says to add in the readme, but I get this when I try to compile:

"Caused by: java.lang.ClassNotFoundException: Didn't find class "com.triggertrap.seekarc.SeekArc" on path: DexPathList[[zip file "/data/app/com.(package name etc)"

Surely there must be another step??

**Comment by scottyab** [comment]
Check the latest version 1.1 and include via jitpack.io link. If there's still an issue please post more information about your setup, i.e Android Studio, SDK versions, build.gradle files etc.
