### ISSUE TITLE
Disable touch events

### ISSUE THREAD

**Issue by scottyab** [Triggertrap/SeekArc#3]
attribute and code way of disabling touch events and ideally remove the scrubber. - Great library btw, i'll send PR with this when I have a sec

**Comment by Leon-Kang-Lee** [comment]
Use following code

        mSeekArc.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                return true;
            }
        });

**Comment by scottyab** [comment]
Fixed in v1.1
