### ISSUE TITLE
Attribute "max" and "progress" has already been defined

### ISSUE THREAD

**Issue by QitmentX7** [Triggertrap/SeekArc#51]
Hello dear friend!
I have this error:
Myproject\app\build\intermediates\res\merged\debug\values\values.xml
Error:(128) Attribute "progress" has already been defined
Error:(128) Attribute "max" has already been defined
Please fix this!

**Comment by voghDev** [comment]
Have a look at your `app/build.gradle` - section `dependencies`. Maybe another library is defining `max` and `progress` attributes on its attrs.xml.

If it's your own lib, I suggest you to rename your attributes to a non-clashing ones.
If it's not yours, I'd suggest you to fork the repository, change the attribute names to a non-clashing ones, such as `seekArc_progress` or `seekArc_max`, and send a PR to @neild001.
