### ISSUE TITLE
Locking the SeekArc when 360 is reached, instead of starting from 0

### ISSUE THREAD

**Issue by voghDev** [Triggertrap/SeekArc#54]
Hi Neil,

thanks for the awesome work on this fantastic widget. I'm trying to adapt it to avoid more than one "full-turn". that means, when you reach 360 degrees, I want the SeekArc to get stuck in there, instead of starting again from zero. I Had no success yet.

Would you suggest any way to approach this requirement? any ideas or pseudo-code that comes in your mind?
If I find an elegant solution, i'll define a new attribute like `lockFullTurn` or similar, and send you a PR

Thanks in advance :)

**Comment by voghDev** [comment]
Nevermind. I finally don't need it because I've changed my requirements to bypass this issue. Issue closed :+1:

**Comment by tuancoltech** [comment]
Hey voghDev,
I got a similar issue here.
Do you have any suggestion to achieve that?

Thanks,

**Comment by gdaniels** [comment]
There's a solution for this on https://github.com/neild001/SeekArc/pull/33.  Ideally someone who has more time and energy should fork and republish this library, updating to more recent APIs and responding to the issues and PRs that have accumulated over time.

**Comment by tuancoltech** [comment]
Thanks gdaniels,
I'll give it a try.

**Comment by tuancoltech** [comment]
Hi gdaniels,

I tried both setting jumpAllowed either from xml or java code but it doesn't seem to take any effect.
The seekbar still keeps going once it reaches the end.

Just copied all the changes you in your PR.
Do you think there's any problem here?

**Comment by gdaniels** [comment]
Hey @tuancoltech - I'm not sure what you were trying but I just updated the PR to be buildable with Android Studio 2.3.3 and altered the sample app in the PR to include the `jumpAllowed="false"` attribute on the basic sample.  Works as expected for me - let me know if you see something different?
