### ISSUE TITLE
Set max programmatically

### ISSUE THREAD

**Issue by androidergor** [Triggertrap/SeekArc#6]
Hi! Thank you for your great work, its great. I have one question, how can I set  seekarc:max="value" programmatically? to set it dynamically. Thank you

**Comment by Ankita1405** [comment]
hello can i know how to set Max dynamically ?

**Comment by Ankita1405** [comment]
Please Tell Its Urgent

**Comment by scottyab** [comment]
fix will be added to v1.2

**Comment by mreram** [comment]
I've upgraded , you can see this repository
https://github.com/mreram/SeekArc
