### ISSUE TITLE
setMin and getMin in not available.

### ISSUE THREAD

**Issue by punithbm** [Triggertrap/SeekArc#60]
Hi there,

Thank you for such a nice library. Is't possible for you to add an option to set and get min value for slider .?

**Comment by subenoeva** [comment]
This repository has no current support. There's a workaround tho.
I did this:
1- Make a fork of this repository
2- Clone it and add getters/setters for whatever you want
3- git commit & git push over your own fork

Now you just have to use your own fork. I recommend to use this with maven/gradle https://github.com/jitpack/jitpack.io
