### ISSUE TITLE
aar to Maven Central

### ISSUE THREAD

**Issue by snowdream** [Triggertrap/SeekArc#9]
@ascorbic @Ross-Gibson @ScottMellors @isharq @neild001  please publish aar to Maven Central,Thank You.

**Comment by scottyab** [comment]
+1 for published (+10 for merging some of the PR's ;)) however using [Jitpack.io](https://jitpack.io/#TriggerTrap/SeekArc/f84ade705e) you don't need it to be on Maven Central 

```groovy
repositories {
	    maven {
	        url "https://jitpack.io"
	    }
	}

	dependencies {
	        compile 'com.github.TriggerTrap:SeekArc:f84ade705e'
	}
```

**Comment by azizimusa** [comment]
what about gradle dependencies ?

**Comment by scottyab** [comment]
updated to v1.1 - https://jitpack.io/#Triggertrap/SeekArc/v1.1
